export default {
  bitcoin: 'bitcoin',
  litecoin: 'litecoin',
  bitcoin_cash: 'bitcoin_cash',
  bitcoin_gold: 'bitcoin_gold',
  ethereum: 'ethereum',
  ethereum_classic: 'ethereum_classic',
  monero: 'monero',
  ripple: 'ripple',
  zcash: 'zcash',
  tether: 'tether',
  unobtamium: 'unobtamium',
  dash: 'dash',
  iota: 'iota',
  stellar: 'stellar',
  neo: 'neo',
  ubiq: 'ubiq',
  dogecoin: 'dogecoin',

  // on the roadmap
  // cardano: 'cardano',
  // walton_chain: 'walton_chain',
  // qtum: 'qtum',
  // wavescoin: 'wavescoin',
  // siacoin: 'siacoin',
  // decred: 'decred',
};