export default {
  bitcoin: 'BTC',
  litecoin: 'LTC',
  dogecoin: 'DOGE',
  dash: 'DASH',
  bitcoin_cash: 'BTH',
  bitcoin_gold: 'BTG',
  ethereum: 'ETH',
  omise_go: 'OMG',
  augur: 'REP',
  eos: 'EOS',
  fuel: 'FUEL',
  status: 'SNT',
  singularDTV: 'SNGLS',
  genesis_coin: 'GEN',
  walton_chain: 'WTC',
  ethereum_classic: 'ETC',
  monero: 'XMR',
  ripple: 'XRP',
  zcash: 'ZEC',
  tether: 'USDT',
  unobtamium: 'UNO',
  iota: 'IOTA',
  stellar: 'XLM',
  neo: 'NEO',
  ubiq: 'UBQ',
  qtum: 'QTUM',

  // on the roadmap
  // cardano: 'cardano',
  // wavescoin: 'wavescoin',
  // siacoin: 'siacoin',
  // decred: 'decred',
};